### ISSUE TITLE
This code is terrible and the project doesn't even build on Android Studio

### ISSUE THREAD

**Issue by Onheiron** [SiliconLabs/EFRConnect-android#5]
The code in this project is very obscure and relies heavily on side-effects and external modifications.
I'm struggling with my implementation of the OTA protocol, but I'm definitely never gonna copy paste your code in my project.
I see in the code you need to add some 0xFF byte to pad the ota_data when not divisible by 4, but nothing about this is mentioned in your documentation.

**Comment by silabs-tiago** [comment]
Hi,

That limitation with ota_data was due to an issue on the embedded side and it's still there to keep compatibility with those older SDKs.

For OTA you can reference our application note [AN1086: Using the Gecko Bootloader with the Silicon Labs Bluetooth® Applications](https://www.silabs.com/documents/public/application-notes/an1086-gecko-bootloader-bluetooth.pdf). This document points you to the OTA host code in the SDK which you can use as reference for your own implementation.

Could you please provide some more insight into your comments on the project structure and code so that we can improve it moving forward?

Regards,
Tiago
