### ISSUE TITLE
It was not built on the latest Android Studio (3.x).

### ISSUE THREAD

**Issue by jeesang7** [SiliconLabs/EFRConnect-android#8]
Do you have any feedback to support the latest android studio ?

**Comment by taozhixiang** [comment]
I have the same problem。Did you solve it?

**Comment by jeesang7** [comment]
Unfortunately, I didn't solve it. @taozhixiang

**Comment by silabs-tiago** [comment]
Hi,

When you import the project to the latest Android studio you will see errors related with missing dependencies. This is because the project was created with older modules which are not installed by default by android studio so the need to install them will pop as the build progresses.

If you install those dependencies then the project will build fine. We just tested this using the latest available android studio as of today and the apk was generated successfully.

Regards,
Tiago

**Comment by lala74** [comment]
With the lastest android studio, you have to downgrade the NDK version to r8e.
Follow this link and my problem go away: 
https://stackoverflow.com/questions/36894961/how-to-downgrade-ndk-to-r8e
